name: TiCS

on: [pull_request, workflow_dispatch]

jobs:
  TiCS:
    name: TiCS
    runs-on: ubuntu-latest
    steps:
    #- name: Build Env
    #  run: apt update && apt install -y --no-install-recommends apt-utils build-essential sudo git nodejs curl
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build project
      run: cd linuxdoom-1.10 && mkdir linux && make
    - name: TICS Client Analysis
      uses: tiobe/tics-github-action@v2
      with:
        projectName: DOOM
        ticsConfiguration: 'https://testlab.tiobe.com/tiobeweb/releasetest/api/cfg?name=default'
        installTics: true
        recalc: 'ALL,GATE'
        filelist: .
        ticsAuthToken: ${{secrets.RELEASETESTTOKEN}}
        githubToken: ${{secrets.GITHUB_TOKEN}}
        
