name: TiCS

on: [pull_request, workflow_dispatch]

jobs:
  TiCS:
    name: TiCS
    runs-on: ubuntu-latest
    steps:
    - name: Build Env
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends apt-utils build-essential curl libx11-dev libxext-dev libnsl2
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build project
      run: |
        mv linuxdoom-1.10/* ./
        mkdir linux
        make
    - name: TICS Client Analysis
      uses: tiobe/tics-github-action@v3
      with:
        project: DOOM
        viewerUrl: 'https://testlab.tiobe.com/tiobeweb/releasetest/api/cfg?name=shared-cfg'
        installTics: true
        filelist: .
        recalc: GATE
        ticsAuthToken: ${{secrets.RELEASETESTTOKEN}}
        
